service: ml-numbers-serverless-api
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!ml-model/**'
    - '!LICENSE'
    - '!test.json'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  # Don't change
  stage: 'prod'
  # Don't change
  region: us-east-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  httpApi:
    cors:
      allowedOrigins: 
        - '*'
      allowedHeaders: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      origin: '*'
      headers: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
  restApi:
    cors:
      allowedOrigins: 
        - '*'
      allowedHeaders: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      origin: '*'
      headers: 
        - X-Recaptcha-Token
        - x-recaptcha-token
        - origin
        - Origin
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent

functions:
  getNumberPrediction:
    handler: handler.handler
    events:
      - http:
          path: /predict
          method: post
          cors: true
    tags:
      app: numbers.gonzalohirsch.com
